export const ideas = [
    {
        imageAlt : "groove moves",
        imagePath : "Assets/lisdin-ideas/featured/groove-moves.svg",
        title: "GrooveMove",
        description: "A new way to work out",
        likesCount : "0",
        commentsCount: "0",
    },
    {
        imageAlt : "under art",
        imagePath : "Assets/lisdin-ideas/featured/under_art.svg",
        title: "UnderArt",
        description: "Promote your new works for others to speculate",
        likesCount : "0",
        commentsCount: "0",
    },
    {
        imageAlt : "neon",
        imagePath : "Assets/lisdin-ideas/latest/neon.svg",
        title: "Neon",
        description: "Choose your color choice of light",
        likesCount : "0",
        commentsCount: "0",
    },
    {
        imageAlt : "quick place",
        imagePath : "Assets/lisdin-ideas/latest/quick-place.svg",
        title: "Quick Place",
        description: "The newest and most efficient way to move in",
        likesCount : "0",
        commentsCount: "0",
    },
    {
        imageAlt : "dn",
        imagePath : "Assets/lisdin-ideas/recommendations/dn.svg",
        title: "DN",
        description: "Drink now while you still can",
        likesCount : "0",
        commentsCount: "0",
    },
    {
        imageAlt : "crash",
        imagePath : "Assets/lisdin-ideas/recommendations/crash.svg",
        title: "Crash",
        description: "Hangout and meet new friends",
        likesCount : "0",
        commentsCount: "0",
    },
]